version: "3.7"
services:
  html2pdf:
    image: index.docker.io/imqs/html2pdf:latest
    ports:
      - "80:80"
    init: true
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup=true
